config/routes.rb
Rails.application.routes.draw do
  resources :ingredients

  resources :recipes
  resources :books

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many(:recipes)
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
		has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to(:book)
	has_and_belongs_to_many :ingredients

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit! #(:title, :cuisine, :chef, :image)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :measurement, :image)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    puts recipe_params
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit! #(:name, :course, :cooktime, :servingsize, :instructions, :image, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this foo from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <br>
  <%= f.label :cuisine %>
  <%= f.text_field :cuisine %>
  <br>
  <%= f.label :chef %>
  <%= f.text_field :chef %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <div class="input-group">
<% Recipe.order(:name).each do |recipe| %>
   <span class="input-group-addon">
    <%= recipe.name %>
    <%= check_box_tag 'book[recipe_ids][]', recipe.id, recipe.in?(@book.recipes), {class: "checkbox inline"} %>
    </span>
<% end %>
</div>
  <p>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Book', new_book_path) %>
  </li>
</ul>

<% @books.each do |book| %>
  <div class="row">
     <div class="col-md-3 col-sm-3">
      <p class="lead"><%= link_to(book.title, book, {:class=> "book_link_style"}) %></p>
      <p class="text-info"><%= book.cuisine %></p>
      <p class="text-warning"><%= book.chef %></p>
    </div>
    <div class="col-md-8 col-sm-8">
      <%= image_tag(book.image) %>
    </div>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to 'New Book', new_book_path  %></li>
  <li><%= link_to('Delete Book', @book, :method => :delete, :confirm => 'Are you sure?') %></li>
  <li><%= link_to('Edit Book', edit_book_path(@book)) %></li>
</ul>

<div class="row">
     <div class="col-md-3">
      <p class="lead"><%= link_to(@book.title, @book) %></p>
      <p class="text-info"><%= @book.cuisine %></p>
      <p class="text-info"><%= @book.chef %></p>
    </div>
    <div class="col-md-8">
      <p class="text-warning"><%= image_tag(@book.image) %></p>
    </div>
</div>

<br>

<!-- SHOW LIST OF RECEPIES HERE -->
<% @book.recipes.each do |recipe| %>

 <div class="row">
    <div class="col-md-5 col-sm-5">
      <p class="lead"><%= recipe.name %></p>
      <%= image_tag(recipe.image) %>
    </div>
  </div>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :measurement %><br>
    <%= f.text_field :measurement %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Measurement</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.measurement %></td>
        <td><%= ingredient.image %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<p>
  <strong>Measurement:</strong>
  <%= @ingredient.measurement %>
</p>

<p>
  <strong>Image:</strong>
  <%= @ingredient.image %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/_header.html.erb
<div class="row"> 
  <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Le Cook Book App</a>
  </div>
  <div class="navbar-header navbar-right">
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li class="active">
      <%= link_to('Books', books_path) %></li>
      <li><%= link_to('Recipes', recipes_path) %></li>
      <li><%= link_to('Ingredients', ingredients_path() ) %></li>
    </ul>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookbookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.0/css/bootstrap.min.css">
</head>
<body>

<div class="container">

  <%= render 'layouts/header' %>

  <div class="row">
    <div class="col-md-12 col-sm-12">
      <%flash.each do|key,value|%>
              <div class="alert alert-<%=key%>"> <%=value%>
      <%end%>
      <%= yield %>
    </div>
  </div>
    
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course %>
  </div>
  <div class="field">
    <%= f.label :cooktime %><br>
    <%= f.number_field :cooktime %>
  </div>
  <div class="field">
    <%= f.label :servingsize %><br>
    <%= f.number_field :servingsize %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_area :image %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.number_field :book_id %>
  </div>

  <h1> Ingredients select goes here </h1>
  
  <div class="input-group">

  <% Ingredient.order(:name).each do |ingredient| %>

  <span class="input-group-addon">


  <%= ingredient.name %>

  <%= check_box_tag('recipe[ingredient_ids][]', ingredient.id, ingredient.in?(@recipe.ingredients), {class: "checkbox inline"}) %>
  

  </span>

  <% end %>

</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Recipe', new_recipe_path) %>
  </li>
</ul>


<% @recipes.each do |recipe| %>
  <div class="row">
     <div class="col-md-4 col-sm-4">
      <p class="lead"><%= link_to(recipe.name, recipe) %>
      <p>Course: <%= recipe.course %>
      <p>Cook time: <%= recipe.cooktime %>
      <p>Serving size: <%= recipe.servingsize %>
      <p><strong>Instructions:</strong><br> <%= recipe.instructions %>
    </div>
     <div class="col-md-8 col-sm-8">
      <p><%= image_tag(recipe.image) %>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Recipe', new_recipe_path) %></li>
  <li><%= link_to('Edit Recipe', edit_recipe_path(@recipe)) %></li>
  <li><%= link_to('Delete Recipe', @recipe, :method => :delete, :confirm => 'Are you sure?') %></li>
  <div class='spacer'></div>
</ul>

<div class="row">
  <div class="col-md-5 col-sm-5">
    <p class="lead"><%= @recipe.name %></p>
    <%= image_tag(@recipe.image, size: "40x40") %>
  </div>

  <div class="col-md-7 col-sm-7">
   <% @recipe.ingredients.each do |ingredient|  %>
      <p><%= ingredient.name %></p>
      <%= image_tag(ingredient.image, size: "40x40")  %>
   <% end %>
  </div>
 </div>